# Generated by Django 3.0.8 on 2020-08-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jq_qualification', models.TextField()),
                ('j_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.Job')),
            ],
        ),
    ]
