# Generated by Django 3.0.8 on 2020-10-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User_Employeer')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User_Employee')),
            ],
        ),
    ]
