# Generated by Django 3.0.8 on 2020-08-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobportal', '0002_jobqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User_Employee')),
                ('j_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.Job')),
            ],
        ),
    ]
