# Generated by Django 3.0.8 on 2020-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_first_name', models.CharField(max_length=100)),
                ('e_last_name', models.CharField(max_length=100)),
                ('e_username', models.CharField(max_length=100)),
                ('e_password', models.CharField(max_length=100)),
                ('e_email', models.CharField(max_length=100)),
                ('e_mobileno', models.CharField(max_length=10)),
                ('e_add1', models.CharField(max_length=100)),
                ('e_city', models.CharField(max_length=100)),
                ('e_state', models.CharField(max_length=100)),
                ('e_country', models.CharField(max_length=100)),
                ('e_qualification', models.CharField(max_length=100)),
                ('e_image', models.ImageField(upload_to='pics/employee')),
                ('e_resume', models.FileField(upload_to='resumes')),
                ('e_sort_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Employeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_full_description', models.TextField()),
                ('c_logo', models.ImageField(upload_to='pics/employeer')),
                ('c_username', models.CharField(max_length=100)),
                ('c_password', models.CharField(max_length=100)),
                ('c_add1', models.CharField(max_length=100)),
                ('c_city', models.CharField(max_length=100)),
                ('c_state', models.CharField(max_length=100)),
                ('c_country', models.CharField(max_length=100)),
                ('c_contact', models.CharField(max_length=10)),
                ('c_email', models.CharField(max_length=100)),
                ('c_website', models.CharField(max_length=100)),
            ],
        ),
    ]
