# Generated by Django 3.0.8 on 2020-11-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_employee',
            name='e_current_role',
            field=models.CharField(default='Software Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employee',
            name='e_experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_employee',
            name='e_jobType',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
